
# --- Excavator Durability Settings ---
DurabilityWoodenExcavator=302 #Durability of the Wooden Excavator | default: 302
DurabilityStoneExcavator=650 #Durability of the Stone Excavator | default: 650
DurabilityIronExcavator=1300 #Durability of the Iron Excavator | default: 1300
DurabilityGoldExcavator=750 #Durability of the Gold Excavator | default: 750
DurabilityLapisExcavator=1100 #Durability of the Lapis Excavator | default: 1100
DurabilityRedstoneExcavator=1100 #Durability of the Redstone Excavator | default: 1100
DurabilityObsidianExcavator=11200 #Durability of the Obsidian Excavator | default: 11200
DurabilityDiamondExcavator=8025 #Durability of the Diamond Excavator | default: 8025
DurabilityEmeraldExcavator=9768 #Durability of the Emerald Excavator | default: 9768
DurabilityNetheriteExcavator=13675 #Durability of the Netherite Excavator | default: 13675

# --- Hammer Durability Settings ---
DurabilityWoodenHammer=302 #Durability of the Wooden Hammer | default: 302
DurabilityStoneHammer=650 #Durability of the Stone Hammer | default: 650
DurabilityIronHammer=1300 #Durability of the Iron Hammer | default: 1300
DurabilityGoldHammer=750 #Durability of the Gold Hammer | default: 750
DurabilityLapisHammer=1100 #Durability of the Lapis Hammer | default: 1100
DurabilityRedstoneHammer=1100 #Durability of the Redstone Hammer | default: 1100
DurabilityObsidianHammer=11200 #Durability of the Obsidian Hammer | default: 11200
DurabilityDiamondHammer=8025 #Durability of the Diamond Hammer | default: 8025
DurabilityEmeraldHammer=9768 #Durability of the Emerald Hammer | default: 9768
DurabilityNetheriteHammer=13675 #Durability of the Netherite Hammer | default: 13675

# --- Excavator Radius Settings ---
RadiusWoodenExcavator=1 #Excavation radius for Wooden Excavator (radius 1 = 3×1 area) | default: 1
RadiusStoneExcavator=1 #Excavation radius for Stone Excavator (radius 1 = 3×1 area) | default: 1
RadiusIronExcavator=1 #Excavation radius for Iron Excavator (radius 1 = 3×1 area) | default: 1
RadiusGoldExcavator=1 #Excavation radius for Gold Excavator (radius 1 = 3×1 area) | default: 1
RadiusLapisExcavator=1 #Excavation radius for Lapis Excavator (radius 1 = 3×1 area) | default: 1
RadiusRedstoneExcavator=1 #Excavation radius for Redstone Excavator (radius 1 = 3×1 area) | default: 1
RadiusObsidianExcavator=1 #Excavation radius for Obsidian Excavator (radius 1 = 3×1 area) | default: 1
RadiusDiamondExcavator=1 #Excavation radius for Diamond Excavator (radius 1 = 3×1 area) | default: 1
RadiusEmeraldExcavator=1 #Excavation radius for Emerald Excavator (radius 1 = 3×1 area) | default: 1
RadiusNetheriteExcavator=1 #Excavation radius for Netherite Excavator (radius 1 = 3×1 area) | default: 1

# --- Hammer Radius Settings ---
RadiusWoodenHammer=1 #Hammering radius for Wooden Hammer (radius 1 = 3×1 area) | default: 1
RadiusStoneHammer=1 #Hammering radius for Stone Hammer (radius 1 = 3×1 area) | default: 1
RadiusIronHammer=1 #Hammering radius for Iron Hammer (radius 1 = 3×1 area) | default: 1
RadiusGoldHammer=1 #Hammering radius for Gold Hammer (radius 1 = 3×1 area) | default: 1
RadiusLapisHammer=1 #Hammering radius for Lapis Hammer (radius 1 = 3×1 area) | default: 1
RadiusRedstoneHammer=1 #Hammering radius for Redstone Hammer (radius 1 = 3×1 area) | default: 1
RadiusObsidianHammer=1 #Hammering radius for Obsidian Hammer (radius 1 = 3×1 area) | default: 1
RadiusDiamondHammer=1 #Hammering radius for Diamond Hammer (radius 1 = 3×1 area) | default: 1
RadiusEmeraldHammer=1 #Hammering radius for Emerald Hammer (radius 1 = 3×1 area) | default: 1
RadiusNetheriteHammer=1 #Hammering radius for Netherite Hammer (radius 1 = 3×1 area) | default: 1

